version: '3' 

services:
  db:
    container_name: db
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: proyecto_1
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306


  back: 
    container_name: maquina1_back
    build: ../backend
    restart: always
    ports:
      - "4000:4000"
    networks:
      - default1 

  front:
    depends_on:
      - back
    container_name: maquina1_front
    build: ../frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - default1    
 

networks:
  default1: 
    driver: bridge
  
volumes:
  db-data:
